# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='expuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='expuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='expuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='expuser',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='expuser',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='expuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expuser',
            name='profile',
            field=models.CharField(blank=True, max_length=255, verbose_name='profile'),
        ),
        migrations.AddField(
            model_name='expuser',
            name='tennant_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='expuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='expuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='expuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='username'),
        ),
        migrations.AlterModelTable(
            name='expuser',
            table='api_user',
        ),
    ]
