# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180614_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expuser',
            name='tennant_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='tenant_id'),
        ),
    ]
